using System;

namespace AsyncAwaitExamples
{
    class Program
    {
        static void Main(string[] args)
        {
            //Every async method becomes a class generated by the compiler.
            //Await every task, none-awaited tasks hide exceptions
            //Do not use MethodName().Wait(), the Wait() method, use await instead 
            //If you do not need to return to the calling thread use .ConfigureAwait(false);
            //Everything that does not touch UI code you can use .ConfigureAwait(false), 
            //when multiple awaits in method
            

            Console.WriteLine("Hello World!");
        }
    }
}
